import jsPDF from "jspdf";
import { STATUS_LABEL } from "../lib/statusMap";

const SUISCAN_BASE = "https://suiscan.xyz/testnet/tx";

/**
 * Generate court-ready PDF from on-chain evidence
 * @param {Object} evidence - From getApplicationEvidence
 * @param {string} txDigest - Transaction digest for Explorer link
 */
export function generateRealEvidencePDF(evidence, txDigest) {
  const pdf = new jsPDF();

  /* ===== Header ===== */
  pdf.setFontSize(20);
  pdf.text("Rentinel Evidence Report", 20, 20);

  pdf.setFontSize(11);
  pdf.text(
    "Tamper-proof rental interaction record secured on Sui blockchain.",
    20,
    30
  );

  /* ===== Case Summary ===== */
  pdf.setFontSize(14);
  pdf.text("Case Summary", 20, 50);

  pdf.setFontSize(11);
  pdf.text(`Listing: ${evidence.listing}`, 20, 60);
  pdf.text(`Tenant: ${evidence.tenant}`, 20, 70);
  pdf.text(`Landlord: ${evidence.landlord}`, 20, 80);

  pdf.text(
    `Applied At: ${new Date(evidence.createdAt).toLocaleString()}`,
    20,
    90
  );

  pdf.text(`Status: ${STATUS_LABEL[evidence.status] ?? "Unknown"}`, 20, 100);

  /* ===== Ghosting Legal Note ===== */
  let y = 115;
  if (evidence.status === 3) {
    pdf.setFontSize(13);
    pdf.text("Ghosting Determination", 20, 120);

    pdf.setFontSize(11);
    pdf.text(
      "No landlord response was recorded within the mandated 48-hour window.",
      20,
      130
    );

    pdf.text(
      "This silent non-response is cryptographically timestamped on-chain.",
      20,
      140
    );
    y = 165;
  }

  /* ===== Blockchain Proof ===== */
  pdf.setFontSize(14);
  pdf.text("Blockchain Verification", 20, y);
  y += 10;

  pdf.setFontSize(10);
  pdf.text(`Object ID: ${evidence.objectId}`, 20, y);
  y += 8;
  pdf.text(`Transaction Digest: ${txDigest || "N/A"}`, 20, y);
  y += 8;
  if (txDigest) {
    pdf.text(`Explorer: ${SUISCAN_BASE}/${txDigest}`, 20, y);
    y += 8;
  }

  /* ===== Footer ===== */
  pdf.setFontSize(10);
  pdf.text(
    "Generated by Rentinel — Making rental fairness provable.",
    20,
    280
  );

  const safeName = evidence.listing?.slice(0, 30).replace(/[^a-zA-Z0-9]/g, "-") || "evidence";
  pdf.save(`rentinel-evidence-${safeName}.pdf`);
}
