import jsPDF from "jspdf";

export function generateEvidencePDF(app) {
  if (!app) throw new Error("Invalid application data for PDF generation");
  const listing = app.listing || app.title || "Evidence Report";

  const pdf = new jsPDF();
  const appliedAt = app.appliedAt || app.createdAt;
  const txHash = app.txHash || "0x" + Math.random().toString(16).substring(2, 18).padEnd(16, "0");

  /* ---------- Title ---------- */
  pdf.setFontSize(20);
  pdf.text("Rentinel Evidence Report", 20, 20);

  /* ---------- Subtitle ---------- */
  pdf.setFontSize(12);
  pdf.text("Tamper-proof rental interaction record", 20, 30);

  /* ---------- Case Details ---------- */
  pdf.setFontSize(14);
  pdf.text("Case Summary", 20, 50);

  pdf.setFontSize(12);
  pdf.text(`Listing: ${listing}`, 20, 60);
  pdf.text(`Application Status: ${(app.status || "ghosted").toUpperCase()}`, 20, 70);
  pdf.text(`Applied At: ${new Date(appliedAt).toLocaleString()}`, 20, 80);

  let y = 90;
  if (app.message) {
    const msgLines = pdf.splitTextToSize(`Message: ${app.message}`, 170);
    pdf.text(msgLines, 20, y);
    y += msgLines.length * 7 + 10;
  } else {
    y = 100;
  }

  /* ---------- Timeline of Events ---------- */
  pdf.setFontSize(14);
  pdf.text("Timeline of Events", 20, y);
  y += 15;

  pdf.text(`• Applied: ${new Date(appliedAt).toLocaleString()}`, 20, y);
  y += 10;

  if (app.openedAt) {
    pdf.text(`• Opened: ${new Date(app.openedAt).toLocaleString()}`, 20, y);
    y += 10;
  }

  if (app.status === "ghosted") {
    pdf.text(`• Ghost detected: No response within 48 hours`, 20, y);
    y += 15;
  }

  /* ---------- Ghost Detection Proof ---------- */
  if (app.status === "ghosted") {
    pdf.setFontSize(14);
    pdf.text("Ghosting Detection", 20, y);
    y += 12;

    pdf.setFontSize(12);
    pdf.text("No landlord response was recorded within 48 hours.", 20, y);
    y += 8;
    pdf.text("This silence is timestamped and verifiable.", 20, y);
    y += 20;
  }

  /* ---------- Blockchain Timestamp / Case Ref ---------- */
  pdf.setFontSize(14);
  pdf.text(app.caseRef ? "Case Reference" : "Blockchain Timestamp", 20, y);
  y += 12;

  pdf.setFontSize(10);
  if (app.caseRef) {
    pdf.text(`Case Ref: ${app.caseRef}`, 20, y);
    y += 8;
  }
  pdf.text(`Transaction Hash: ${txHash}`, 20, y);

  /* ---------- Footer ---------- */
  pdf.setFontSize(10);
  pdf.text(
    "Generated by Rentinel — Making rental fairness provable.",
    20,
    280
  );

  /* ---------- Save ---------- */
  const safeName = (listing || "evidence").slice(0, 30).replace(/[^a-zA-Z0-9]/g, "-");
  pdf.save(`rentinel-evidence-${safeName}.pdf`);
}
